### DISCUSSION TITLE
Rounded corners for player image theme

### DISCUSSION THREAD

**Discussion by Dzheremi2** [pear-devs/pear-desktop#2884] [Q&A] [answered]
Does anybody have a rounded corners theme for the album image in player?

**Comment by daika7ana** [comment, marked as answer]
Do you mean something like this:
![image](https://github.com/user-attachments/assets/b2dd4483-d0c9-47a2-8db0-27636c05b096)

If yes, here's the CSS for it:
```css
ytmusic-player {
  background-color: transparent !important;
}

ytmusic-player yt-img-shadow.thumbnail,
ytmusic-player .song-media-controls.ytmusic-player {
  border-radius: 30px !important;
  overflow: hidden !important;
}
```
